{{- range $name, $svc := .Values.services }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ $name }}
spec:
  selector:
    app: {{ $name }}
  ports:
  - port: {{ default $svc.port $svc.servicePort }}
    targetPort: {{ $svc.port }}

{{- end }}
