apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: monitoring-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/meAnshu/Production-Grade_GitOps-Driven_Microservices-Demo.git
    targetRevision: main
    path: observability

    # Explicit directory mode — no Kustomize, no Helm, plain YAML apply
    directory:
      recurse: false

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
